# Generated by Django 5.2 on 2025-11-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='node',
            name='external_urls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='node',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='uri',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
