# Generated by Django 5.2 on 2025-11-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entify', '0002_type_alter_node_attributes_alter_node_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='node',
            old_name='slug',
            new_name='identifier',
        ),
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
